+++
# Date this page was created.
date = "2017-04-11"

# Project title.
title = "Costs of human-ignited wildfires in the U.S. (2001-2015)-from the Wildland-Urban Interface to wildlands "

# Project summary to display on homepage.
summary = "The number of wildfires has increased in the U.S. since 1970. Simultaneously, more homes have been built in areas that meet or intermingle with undeveloped wildland vegetation, creating zones known as the wildland-urban interface (WUI). Communities in these areas are both at risk of wildfire danger and thought to be the primary cause of wildfire ignitions across the U.S. We explored the consequences (fire frequency, burned area, seasonality) and costs (suppression costs, homes destroyed, lives lost) of human vs. lightning-started wildfires, along a gradient from the WUI to wildland areas across the conterminous U.S. (2001-2015). This study illustrates how the WUI, which accounts for only a small portion of U.S. land area (13%), acts as a major source of fires, almost exclusively human-started. WUI fires, in turn, account for a disproportionate number of structures and lives lost, suppression costs, and expand to burn large areas of surrounding wildland. In the WUI, 96% of wildfires started by people, and an average of 0.11% (range: 0.06 - 0.17%), or 867 km2, burned every year. Human-started wildfires originating in the WUI alone resulted \$397 million in suppression costs, 4,717 structures lost, and 20 lives lost. While overall, human-caused wildfires in all lands accounted for 34% of all fire suppression costs ($3.4 billion), 86% (n = 11,226) structures lost, and 90 lives lost. Nearly 40% of all wildfires between 2001-2015 started in the WUI, making these areas a high-priority for policy and management aimed at reducing human ignitions and promoting resilience to future fires."

# Optional image to display on homepage (relative to `static/img/` folder).
image_preview = ""

# Tags: can be used for filtering projects.
# Example: `tags = ["machine-learning", "deep-learning"]`
tags = ["all", "wildfire"]

# Optional external URL for project (replaces project detail page).
external_link = ""

# Does the project detail page use math formatting?
math = false

# Optional featured image (relative to `static/img/` folder).
[header]
image = ""
caption = ""

+++

Improving spoken language use (i.e., discourse skills) is a common treatment goal for children with neurodevelopmental disorders, particularly for those with difficulties in conversational reciprocity, perseverative speech, or idiosyncratic/stereotyped word use. These features are clinically meaningful, and in previous projects, we have successfully applied Natural Language Processing (NLP) methods to measure these discourse skills using natural language samples from children with Autism Spectrum Disorder (ASD). However, while NLP methods yield diagnostically relevant measures, it is not known if they can be translated into meaningful outcome measures. To take this next step, important questions must be addressed: 

* How stable and responsive are NLP discourse measures over time? 
* How consistent are the measures across different measurement contexts and lengths? 
* What is their validity? 
* To what degree are measures impacted by general language or intellectual abilities? 

Lack of knowledge about these psychometric properties of NLP discourse measures is a problem because, without it, the likelihood that children’s use of spoken language can be targeted and impacted in large-scale clinical trials is remote.

The long-term goal of this project is to harness the benefits of NLP to impact functional spoken language outcomes for children with neurodevelopmental disorders. The parent project (R01DC012033: “Computational Characterization of Language Use in Autism Spectrum Disorder”) took the first steps towards this goal by developing NLP algorithms to measure discourse skills based on raw (i.e., not coded or annotated) transcripts. Our strong results indicate difficulties in conversational reciprocity as well as elevated repetitive language behaviors among children with ASD compared to children without ASD, and were not due to differences in age, IQ, or language abilities. Our objective in this project is to take the next step to evaluate the suitability of these NLP automated discourse measures (ADMs) as outcomes for individuals with a range of intellectual abilities and diagnoses. Our approach will focus on optimizing stability of such measures, and assessing responsiveness to change over time, consistency across sampling contexts and sample lengths, and validity. 