+++
abstract = "Understanding disturbance interactions and their ecological consequences remains a major challenge for research on the response of forests to a changing climate. When, where, and how one disturbance may alter the severity, extent, or occurrence probability of a subsequent disturbance is encapsulated by the concept of linked disturbances. Here, we evaluated 1) how climate and forest habitat variables, including disturbance history, interact to drive 2000s spruce beetle (Dendroctonus rufipennis) infestation of Engelmann spruce (Picea engelmannii) across the Southern Rocky Mountains; and 2) how previous spruce beetle infestation affects subsequent infestation across the Flat Tops Wilderness in north- western Colorado, which experienced a severe landscape-scale spruce beetle infestation in the 1940s. We hypothesized that drought and warm temperatures would promote infesta- tion, whereas small diameter and non-host trees, which may reflect past disturbance by spruce beetles, would inhibit infestation. Across the Southern Rocky Mountains, we found that climate and forest structure interacted to drive the 2000s infestation. Within the Flat Tops study area we found that stands infested in the 1940s were composed of higher pro- portions of small diameter and non-host trees ca. 60 years later. In this area, the 2000s in- festation was constrained by a paucity of large diameter host trees (> 23 cm at diameter breast height), not climate. This suggests that there has not been sufficient time for trees to grow large enough to become susceptible to infestation. Concordantly, we found no overlap between areas affected by the 1940s infestation and the current infestation. These results show a severe spruce beetle infestation, which results in the depletion of susceptible hosts, can create a landscape template reducing the potential for future infestations."

authors = ["Sarah Hart", "Thomas T. Veblen", "**Nathan Mietkiewicz**", "Dominik Kulakowski"]
date = "2015-06-22"
image_preview = ""
math = true
publication_types = ["2"]
publication = "In **PlosOne**"
publication_short = ""
selected = false
title = paste0("2015. Negative Feedbacks on Bark Beetle Outbreaks: Widespread and Severe Spruce Beetle Infestation Restricts Subsequent Infestation.", "**PlosOne.**")
url_code = ""
url_dataset = ""
url_pdf = "pdf/2015_Hart_etal_PlosOne.pdf"
url_project = ""
url_slides = ""
url_video = ""

[[url_custom]]
name = "View Journal Article"
url = "http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0127975"

# Optional featured image (relative to `static/img/` folder).
[header]
image = ""
caption = ""

+++
